backend:
  image:
    repository: 596560793647.dkr.ecr.us-east-1.amazonaws.com/fullstack-backend
    tag: latest
  replicas: 2

frontend:
  image:
    repository: 596560793647.dkr.ecr.us-east-1.amazonaws.com/fullstack-frontend
    tag: latest
  replicas: 2

database:
  url: "postgresql://appuser:@{p-e7:@i})LnH*r@app-db-prod.cyj60ga6sq8b.us-east-1.rds.amazonaws.com:5432/appdb"

ingress:
  enabled: true
  className: alb
