name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: 596560793647
  CLUSTER_NAME: demo-eks
  ECR_REPO: fullstack-backend

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596560793647:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
            --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4️⃣ Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build -t $ECR_REPO:${{ github.sha }} ./backend
          docker tag $ECR_REPO:${{ github.sha }} \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}

      # 5️⃣ Push Backend Image to ECR
      - name: Push Backend Image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}

      # 6️⃣ Update kubeconfig for EKS
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      # 7️⃣ Deploy Backend using Helm
      - name: Deploy Backend with Helm
        run: |
          helm upgrade --install fullstack-app ./helm \
            --set backend.image.repository=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO \
            --set backend.image.tag=${{ github.sha }}
